version: '2.3'
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    environment: 
    - SE_OPTS=-browserTimeout 5 -timeout 5
    - GRID_MAX_SESSION=10
    - GRID_TIMEOUT=5
    ports:
    - "127.0.0.1:4444:4444"
    healthcheck:
      test: ["CMD", "sleep", "1s"]
      timeout: 2s
      retries: 2
  node-chrome1:
    image: selenium/node-chrome
    container_name: node-chrome1
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
    - HUB_PORT_4444_TCP_ADDR=selenium-hub
    - HUB_PORT_4444_TCP_PORT=4444
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
    - NODE_BROWSER_TIMEOUT=5
    - NODE_MAX_SESSION=10
    - SE_OPTS=-browserTimeout 5 -timeout 5
    volumes:
    - "/dev/shm:/dev/shm"
  node-chrome2:
    image: selenium/node-chrome
    container_name: node-chrome2
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
    - HUB_PORT_4444_TCP_ADDR=selenium-hub
    - HUB_PORT_4444_TCP_PORT=4444
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
    - NODE_MAX_SESSION=10
    - NODE_BROWSER_TIMEOUT=5
    - SE_OPTS=-browserTimeout 5 -timeout 5
    volumes:
    - "/dev/shm:/dev/shm"
